"""migrate

Revision ID: b52bacef9e55
Revises: 2997f19d1b98
Create Date: 2024-01-17 03:09:00.460338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52bacef9e55'
down_revision = '2997f19d1b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('review_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('review_recipe_id_fkey', 'recipe', ['recipe_id'], ['id'])

    # ### end Alembic commands ###
