"""migrate

Revision ID: c15daeee5198
Revises: b52bacef9e55
Create Date: 2024-01-18 00:53:20.659982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15daeee5198'
down_revision = 'b52bacef9e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.drop_constraint('user_google_id_key', type_='unique')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_google_id_key', ['google_id'])
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###
